### ISSUE TITLE
No module named 'pypupilext._pypupil

### ISSUE THREAD

**Issue by AThanapol** [openPupil/PyPupilEXT#1]
When I run "Main_Test_1.py", It cannot find "_pypupil" that "__init__.py" call.
How can I solve it?
![Capture](https://user-images.githubusercontent.com/112547690/189297879-ce7f1d02-f030-4fd0-9dab-e45dcf1a09ca.PNG)

**Comment by BZandi** [comment]
It could be possible that the compilation did not work. Were there any errors when building the wheel file with ``python setup.py sdist bdist_wheel``?

When installing the package with ``pip install PyPupilEXT-0.0.1-cp37-none-any.whl``, there should be the _pypupil file added into your site-packages folder of your python env (see attached screenshot). Maybe you need to copy the _pypupil file manually into the site-packages folder or the installation failed. However, note that I did not yet tested the installation on windows (only on macOS).

<img width="941" alt="Screen" src="https://user-images.githubusercontent.com/62992112/189387930-d21c8c9d-cdee-45ec-976f-7f53a59429d7.png">

**Comment by BZandi** [comment]
It could be possible that the compilation did not work. Were there any errors when building the wheel file with ``python setup.py sdist bdist_wheel``?

When installing the package with ``pip install PyPupilEXT-0.0.1-cp37-none-any.whl``, there should be the _pypupil file added into your site-packages folder of your python env (see attached screenshot). Maybe you need to copy the _pypupil file manually into the site-packages folder or the installation failed. However, note that I did not yet tested the installation on windows (only on macOS).

<img width="941" alt="Screen" src="https://user-images.githubusercontent.com/62992112/189388539-5e232a42-2cd7-4ea4-a2a8-a37ec904cbc1.png">

**Comment by AThanapol** [comment]
I test the PyPupilEXT on window 10 x64bit.

When create a new python environment, I'm not sure that you use python 3.7 or python 3.9? But I use `conda create -n pypupilenv python=3.7`.
![Capture2](https://user-images.githubusercontent.com/112547690/189821024-d74aab93-5e4f-407e-a1c8-a67863671916.PNG)


Then I build the wheel file with `python setup.py sdist bdist_wheel`. Files in dist folder show in the picture below. 
![dist](https://user-images.githubusercontent.com/112547690/189822331-d8b14971-a72b-41ef-b803-1ba18291a41a.PNG)


When installing the package with `pip install PypupilEXT-0.0.1-cp37-cp37m-win_amd64.whl`, it seems work. But in the pypupilext folder doesn't have _pypupil file.
![Capture](https://user-images.githubusercontent.com/112547690/189822793-1205b985-6c7a-4633-802f-d9069a2bf474.PNG)
![pypupilext](https://user-images.githubusercontent.com/112547690/189823244-f30cf2ca-3d90-4ef7-974b-45b88a264c46.PNG)

**Comment by BZandi** [comment]
You need to check the following folder for the ``_pupil`` file: ``PyPupilEXT/build/lib.win-amd64-3.9/``. Please post a screenshot of the folder's content.

Additionally, you need to check whether pypupilext is installed correctly when using pip. For this, you need to locate your env folder of anaconda, which is, in my case, the folder in the attached screenshot. Please also provide a screenshot of this folder.

![Bildschirmfoto 2022-09-13 um 11 18 46](https://user-images.githubusercontent.com/62992112/189865572-fd427801-aa4a-4645-9b2c-dd1ca67714de.png)

Regarding Python 3.7 or 3.9: It should be python 3.9. I will fix the readme. Thank you.

**Comment by AThanapol** [comment]
I try to use the wheel file that you attach. It's work!
![finish](https://user-images.githubusercontent.com/112547690/190042243-5aa2c461-6dfb-4405-a85c-a67ea165fbf5.PNG)

Thank you so much.

**Comment by BZandi** [comment]
The project has been updated, and the build process should now work smoothly on Windows, Ubuntu, and macOS. The instructions in the README file were revised accordingly.

Further, there are now prebuilt wheel files, so you no longer need to build the project from source if your primary goal is to use it. Here's a link to the wheel files for different platforms: https://github.com/openPupil/PyPupilEXT/releases/tag/v0.0.1-beta
