### ISSUE TITLE
ARM/Silicon Mac Install Instructions

### ISSUE THREAD

**Issue by williamwiebe** [openPupil/PyPupilEXT#9]
Hardware: Apple M1 Max MacBook Pro (2021)
System: Ventura 13.6.2

Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

1. I installed the following packages with homebrew ([specified here](https://github.com/openPupil/PyPupilEXT/blob/main/.github/workflows/action.yml)), after having issues with `cmake` and `nasm` which caused the `ffmpeg` install to fail:

            brew install pkg-config
            brew install cmake
            brew install nasm
            brew install gcc
            brew install llvm
            brew install libomp
            brew install libmpc
            brew install tree

2. After cloning the repository in installation step 1B, I pulled the [current master](https://github.com/oneapi-src/oneTBB/tree/c62b6468508316a1de976921f4c2a596fc1dcd31) of `oneTBB` and replaced the submodule downloaded at PyPupilEXT/3rdparty/oneTBB. This was necessary because the Apple clang compiler failed with [this issue](https://github.com/oneapi-src/oneTBB/issues/370), which has been fixed in subsequent releases.

3. My build finally compiled! Except when I tried to run the files, it threw an `[ImportError: dlopen(): Symbol not found:.... Expected in: flat namespace]` like [this](https://stackoverflow.com/questions/60761175/how-to-solve-importerror-dlopen-symbol-not-found-expected-in-flat-name) and [this](https://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean). I take it it was because PyPupilEXT specifies x86_64/x64 architectures for the compilers, but my clang was compiling for arm64.

* So I changed [setup.py](https://github.com/openPupil/PyPupilEXT/blob/main/setup.py) as follows:
line 81: `cmake_args += ["-DVCPKG_TARGET_TRIPLET=arm64-osx"]`

* Along with [CMakeLists.txt](https://github.com/openPupil/PyPupilEXT/blob/main/CMakeLists.txt):
line 60: `set(VCPKG_TARGET_TRIPLET arm64-osx CACHE STRING "")`
line 61: `set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "")`
line 80: `CMAKE_ARGS -DTBB_TEST=OFF -DCMAKE_INSTALL_PREFIX=build -DCMAKE_OSX_ARCHITECTURES=arm64 -DBUILD_SHARED_LIBS=OFF -DTBBMALLOC_BUILD=OFF -DTBBMALLOC_PROXY_BUILD=OFF`

And now it's running. I think those are all my emendations. Hope this is useful to someone!

**Comment by chuhuiL** [comment]
Hi I am also using m1 and follow your instructions successfully generate whl file but when I try 
pip install PyPupilEXT-0.0.1-cp37-cp37m-macosx_10_15_x86_64.whl
I got this error:
WARNING: Requirement 'PyPupilEXT-0.0.1-cp37-cp37m-macosx_10_15_x86_64.whl' looks like a filename, but the file does not exist
ERROR: PyPupilEXT-0.0.1-cp37-cp37m-macosx_10_15_x86_64.whl is not a supported wheel on this platform.
Did you have this error? How did you solve this? Thank you so much!

**Comment by BZandi** [comment]
Thank you very much for the instructions! I have updated the [CMakeLists.txt](https://github.com/openPupil/PyPupilEXT/blob/main/CMakeLists.txt) and the [setup.py](https://github.com/openPupil/PyPupilEXT/blob/main/setup.py). The build process should now work on Apple Silicon out of the box.
